import { Button } from '../../shared/components/Button.js';
import { Modal } from '../../shared/components/Modal.js';
import { ErrorState, LoadingState, Toast } from '../../shared/components/States.js';
import { CustomerController } from '../customers/CustomerController.js';
import { MockCustomerRepository } from '../customers/repositories/MockCustomerRepository.js';
import { serviceRepository } from '../services/repositories/serviceRepositoryInstance.js';
import { InvoiceController } from './InvoiceController.js';
import { InvoiceDetails } from './components/InvoiceDetails.js';
import { InvoiceForm } from './components/InvoiceForm.js';
import { InvoiceList } from './components/InvoiceList.js';
import { RevenueSummary } from './components/RevenueSummary.js';
import { MockInvoiceRepository } from './repositories/MockInvoiceRepository.js';

function createInvoiceModal(controller, invoice, onComplete) { let modal; const form = InvoiceForm({ invoice, customers: controller.state.customers, services: controller.state.services, onCancel: () => modal.close(), onSubmit: async (values) => { const submit = form.querySelector('button[type="submit"]'); submit.disabled = true; try { if (invoice) { await controller.updateInvoice(invoice.id, values); Toast.success('Invoice updated successfully.'); } else { await controller.createInvoice(values); Toast.success('Invoice created successfully.'); } modal.close(); onComplete(); } catch (error) { submit.disabled = false; form.querySelector('.invoice-form-error').textContent = error.message; } } }); modal = new Modal({ title: invoice ? 'Edit invoice' : 'Create invoice', content: form, className: 'invoice-modal' }); modal.render(); modal.show(); }

export function Billing() { const customerController = new CustomerController(new MockCustomerRepository()); const controller = new InvoiceController(new MockInvoiceRepository(), customerController.repository, serviceRepository); const page = document.createElement('div'); page.className = 'page billing-page'; const header = document.createElement('header'); header.className = 'page-header billing-header'; header.innerHTML = '<div><p class="billing-eyebrow">Finance workspace</p><h1>Billing & Invoices</h1><p class="billing-subtitle">Keep invoice records clear, consistent, and ready to share.</p></div>'; header.appendChild(new Button({ label: '+ Create invoice', variant: 'primary', onClick: () => createInvoiceModal(controller, null, render) }).render()); page.appendChild(header); const content = document.createElement('div'); content.className = 'page-content billing-content'; page.appendChild(content);
  function render() { const state = controller.state; if (state.loading) { content.replaceChildren(new LoadingState({ message: 'Loading invoices...', className: 'billing-loading' }).render()); return; } if (state.error) { content.replaceChildren(new ErrorState({ title: 'Unable to load invoices', message: state.error, retry: new Button({ label: 'Try again', variant: 'secondary', onClick: () => controller.load() }) }).render()); return; } if (state.selectedInvoice) { content.replaceChildren(InvoiceDetails({ invoice: state.selectedInvoice, onBack: () => controller.clearSelection(), onEdit: () => createInvoiceModal(controller, state.selectedInvoice, render) })); return; } content.replaceChildren(RevenueSummary(controller.getSummary())); const listHeading = document.createElement('div'); listHeading.className = 'billing-list-heading'; listHeading.innerHTML = `<h2>Invoice list</h2><span>${state.invoices.length} invoices</span>`; content.appendChild(listHeading); content.appendChild(InvoiceList({ invoices: controller.getEnrichedInvoices(), onSelect: (id) => controller.selectInvoice(id), onEdit: async (id) => createInvoiceModal(controller, controller.resolveInvoice(await controller.repository.getById(id)), render) })); }
  controller.subscribe(render); render(); controller.load(); return page; }
